/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vbhook_VBHook */

#ifndef _Included_vbhook_VBHook
#define _Included_vbhook_VBHook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vbhook_VBHook
 * Method:    create_vb_client
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_vbhook_VBHook_create_1vb_1client
  (JNIEnv *, jobject);

/*
 * Class:     vbhook_VBHook
 * Method:    create_vb
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_vbhook_VBHook_create_1vb
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vbhook_VBHook
 * Method:    free_vb
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vbhook_VBHook_free_1vb
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vbhook_VBHook
 * Method:    free_vb_client
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vbhook_VBHook_free_1vb_1client
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vbhook_VBHook
 * Method:    init_glue
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vbhook_VBHook_init_1glue
  (JNIEnv *, jobject);

/*
 * Class:     vbhook_VBHook
 * Method:    terminate_glue
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vbhook_VBHook_terminate_1glue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
